#!/usr/bin/env bash
# Writes the deployment for N seats: stream/docker-compose.yml (one streaming
# container per seat), stream/slots.json (what the lobby manages), stream/slots/*.env
# (each seat's session, written by the lobby) and stream/Caddyfile (one address: the
# lobby at /, the seats at /slotN/).
#
#   bash stream/gen.sh 5        # five friends can play at once
#   cd stream && docker compose build && docker compose create   # build once, create stopped
#   cd server && bundle exec ruby ../stream/lobby/lobby.rb          # the website
#
# Env (or stream/.env before running, which is read and kept):
#   PUBLIC_IP   the address your friends reach (required for WebRTC; LAN IP or public IP)
#   PEMK_HOST   where the containers find the PEMK server (host.docker.internal = this machine)
#   PEMK_PORT   its port (9998)
#   DOMAIN      a domain for https (Let's Encrypt through Caddy); without one, plain http on port 80
#   SCREEN/FPS  the virtual screen (1024x768) and frame rate (30)
set -euo pipefail
cd "$(dirname "$0")"
n="${1:-}"
[[ "$n" =~ ^[1-9][0-9]?$ ]] || { echo "usage: gen.sh <number of seats, 1-99>"; exit 1; }
[ -f .env ] && set -a && . ./.env && set +a
: "${PUBLIC_IP:=}"
: "${PEMK_HOST:=host.docker.internal}"
: "${PEMK_PORT:=9998}"
: "${DOMAIN:=}"
: "${SCREEN:=1024x768}"
: "${FPS:=30}"
: "${ADMIN_PASSWORD:=$(head -c 12 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 12)}"
: "${LOBBY_SECRET:=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)}"
if [ -n "$DOMAIN" ]; then COOKIE_SECURE=true; else COOKIE_SECURE=false; fi

{
  echo "PUBLIC_IP=${PUBLIC_IP}"
  echo "PEMK_HOST=${PEMK_HOST}"
  echo "PEMK_PORT=${PEMK_PORT}"
  echo "DOMAIN=${DOMAIN}"
  echo "SCREEN=${SCREEN}"
  echo "FPS=${FPS}"
  echo "SEATS=${n}"
  echo "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
  echo "LOBBY_SECRET=${LOBBY_SECRET}"
  echo "COOKIE_SECURE=${COOKIE_SECURE}"
} > .env.new && mv .env.new .env

mkdir -p slots
{
  echo "# Generated by stream/gen.sh - one streaming container per seat, managed by the lobby."
  echo "# Regenerate with: bash stream/gen.sh $n"
  echo "name: pemk-play"
  echo "services:"
  for ((i = 0; i < n; i++)); do
    s="slot$((i + 1))"; web=$((8081 + i)); lo=$((52000 + i * 20)); hi=$((lo + 19))
    [ -f "slots/${s}.env" ] || : > "slots/${s}.env"
    chmod 600 "slots/${s}.env"
    cat <<SVC
  ${s}:
    build:
      context: ..
      dockerfile: stream/Dockerfile
    image: pemk-play
    restart: "no"
    shm_size: "1gb"
    ports:
      - "127.0.0.1:${web}:8080"
      - "${lo}-${hi}:${lo}-${hi}/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - slots/${s}.env
    environment:
      PEMK_INSTANCE: ${s}
      PEMK_HOST: \${PEMK_HOST}
      PEMK_PORT: \${PEMK_PORT}
      PEMK_SCREEN: \${SCREEN}
      NEKO_DESKTOP_SCREEN: \${SCREEN}@\${FPS}
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: \${ADMIN_PASSWORD}
      NEKO_SESSION_IMPLICIT_HOSTING: "true"
      NEKO_SESSION_COOKIE_ENABLED: "true"
      NEKO_SESSION_COOKIE_PATH: /${s}/
      NEKO_SESSION_COOKIE_SECURE: "\${COOKIE_SECURE}"
      NEKO_SERVER_PATH_PREFIX: /${s}/
      NEKO_SERVER_PROXY: "true"
      NEKO_WEBRTC_EPR: ${lo}-${hi}
      NEKO_WEBRTC_NAT1TO1: \${PUBLIC_IP}
    volumes:
      - ${s}-wine:/home/neko/.wine
SVC
  done
  echo "volumes:"
  for ((i = 0; i < n; i++)); do echo "  slot$((i + 1))-wine:"; done
} > docker-compose.yml

{
  echo "["
  for ((i = 0; i < n; i++)); do
    printf '  {"name": "slot%d", "web_port": %d}%s\n' "$((i + 1))" "$((8081 + i))" "$([ $i -lt $((n - 1)) ] && echo ,)"
  done
  echo "]"
} > slots.json

# One address. The lobby at /, each seat at /slotN/ (neko serves under that prefix and
# sets its cookie for that path). WebRTC media goes straight to the UDP ranges.
{
  echo "# Generated by stream/gen.sh."
  echo "${DOMAIN:-http://:80} {"
  for ((i = 0; i < n; i++)); do
    echo "  handle /slot$((i + 1))/* {"
    echo "    reverse_proxy 127.0.0.1:$((8081 + i))"
    echo "  }"
  done
  echo "  handle {"
  echo "    reverse_proxy 127.0.0.1:8090"
  echo "  }"
  echo "}"
} > Caddyfile

echo "wrote stream/docker-compose.yml (${n} seats), stream/slots.json, stream/slots/*.env, stream/Caddyfile"
if [ -n "$DOMAIN" ]; then echo "the website: https://${DOMAIN}/"; else echo "the website: http://${PUBLIC_IP:-<this host>}/"; fi
[ -n "$PUBLIC_IP" ] || echo "set PUBLIC_IP (the address your friends reach) in stream/.env and run again, or WebRTC will not connect"
