#!/usr/bin/env bash
# Writes stream/docker-compose.yml, stream/.env and stream/Caddyfile for the players
# you name: one game container each, its own password, web port and WebRTC port range.
#
#   bash stream/gen.sh ash misty brock          # then: cd stream && docker compose up --build
#
# Env (or stream/.env before running, which is read and kept):
#   PUBLIC_IP   the address your friends reach (required for WebRTC; LAN IP or public IP)
#   PEMK_HOST   where the game containers find the PEMK server (default: host.docker.internal,
#               i.e. the server running on this machine; use the LAN IP on Linux)
#   PEMK_PORT   its port (9998)
#   DOMAIN      optional: a domain for one https address with a path per player (Caddyfile)
#   SCREEN      the virtual screen (1024x768)
#   FPS         its frame rate (30)
set -euo pipefail
cd "$(dirname "$0")"
[ $# -ge 1 ] || { echo "usage: gen.sh <player> [player...]"; exit 1; }
[ -f .env ] && set -a && . ./.env && set +a
: "${PUBLIC_IP:=}"
: "${PEMK_HOST:=host.docker.internal}"
: "${PEMK_PORT:=9998}"
: "${DOMAIN:=}"
: "${SCREEN:=1024x768}"
: "${FPS:=30}"
: "${ADMIN_PASSWORD:=$(head -c 12 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 12)}"

for p in "$@"; do
  [[ "$p" =~ ^[a-z0-9_-]+$ ]] || { echo "player names: lowercase letters, digits, - and _ only ($p)"; exit 1; }
done

# .env: the shared settings and one password per player, kept across runs.
{
  echo "PUBLIC_IP=${PUBLIC_IP}"
  echo "PEMK_HOST=${PEMK_HOST}"
  echo "PEMK_PORT=${PEMK_PORT}"
  echo "DOMAIN=${DOMAIN}"
  echo "SCREEN=${SCREEN}"
  echo "FPS=${FPS}"
  echo "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
  for p in "$@"; do
    var="PASSWORD_${p^^}"; var="${var//-/_}"
    pw="${!var:-$(head -c 12 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 10)}"
    echo "${var}=${pw}"
  done
} > .env.new && mv .env.new .env
set -a && . ./.env && set +a

{
  echo "# Generated by stream/gen.sh - one game per player, streamed to a browser tab."
  echo "# Regenerate with: bash stream/gen.sh $*"
  echo "name: pemk-play"
  echo "services:"
  i=0
  for p in "$@"; do
    var="PASSWORD_${p^^}"; var="${var//-/_}"
    web=$((8081 + i)); lo=$((52000 + i * 20)); hi=$((lo + 19))
    cat <<SVC
  play-${p}:
    build:
      context: ..
      dockerfile: stream/Dockerfile
    image: pemk-play
    restart: unless-stopped
    shm_size: "1gb"
    ports:
      - "${web}:8080"
      - "${lo}-${hi}:${lo}-${hi}/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PEMK_INSTANCE: ${p}
      PEMK_HOST: \${PEMK_HOST}
      PEMK_PORT: \${PEMK_PORT}
      PEMK_SCREEN: \${SCREEN}
      NEKO_DESKTOP_SCREEN: \${SCREEN}@\${FPS}
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: \${${var}}
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: \${ADMIN_PASSWORD}
      NEKO_SESSION_IMPLICIT_HOSTING: "true"
      NEKO_WEBRTC_EPR: ${lo}-${hi}
      NEKO_WEBRTC_NAT1TO1: \${PUBLIC_IP}
      NEKO_SERVER_PATH_PREFIX: /${p}/
    volumes:
      - play-${p}-wine:/home/neko/.wine
SVC
    i=$((i + 1))
  done
  echo "volumes:"
  for p in "$@"; do echo "  play-${p}-wine:"; done
} > docker-compose.yml

# One https address, a path per player, TLS from Let's Encrypt: `caddy run` next to
# the containers (or add it as a service). WebRTC media still uses the UDP ranges.
{
  echo "# Generated by stream/gen.sh. https://${DOMAIN:-play.example.com}/<player>/"
  echo "${DOMAIN:-play.example.com} {"
  i=0
  for p in "$@"; do
    echo "  handle /${p}/* {"
    echo "    reverse_proxy 127.0.0.1:$((8081 + i))"
    echo "  }"
    i=$((i + 1))
  done
  echo "  respond 404"
  echo "}"
} > Caddyfile

echo "wrote stream/docker-compose.yml, stream/.env, stream/Caddyfile"
i=0
for p in "$@"; do
  var="PASSWORD_${p^^}"; var="${var//-/_}"
  if [ -n "$DOMAIN" ]; then url="https://${DOMAIN}/${p}/"; else url="http://${PUBLIC_IP:-<this host>}:$((8081 + i))/${p}/"; fi
  echo "  ${p}: ${url}  user 'neko', password ${!var}"
  i=$((i + 1))
done
[ -n "$PUBLIC_IP" ] || echo "set PUBLIC_IP (the address your friends reach) in stream/.env and run again, or WebRTC will not connect"
